export default {
  GET_TG_BOOKS: "get-tg-books",
  GET_TG_GIFTS: "get-tg-gifts",
  GET_TG_USERS: "get-tg-users",
  CREATE_TG_BOOK: 'create-tg-book',
  CREATE_TG_GIFT: 'create-tg-gift',
  GET_TG_ORDER_HISTORY: 'get-tg-order-history',
  GET_TG_SINGLE_GIFT: "get-tg-single-gift",
  GET_TG_SINGLE_BOOK: "get-tg-single-book",
  GET_TG_SINGLE_USER: "get-tg-single-user",
  GET_TG_SINGLE_ORDER: 'get-tg-single-order',
  UPDATE_TG_BOOK: "update-tg-book",
  UPDATE_TG_GIFT: "update-tg-gift",
  FULFILLED: "_FULFILLED",
  REJECTED: "_REJECTED",
  PENDING: "_PENDING",
};
